### ISSUE TITLE
Improve contrast of hover over on buttons.

### ISSUE THREAD

**Issue by cawooda** [cawooda/circle#5]
button hovering us currently showing text as white which effectively makes it disapear

**Comment by cawoodm** [comment]
Is [this](https://github.com/cawooda/circle/blob/main/client/src/components/styles/ButtonStyle.js#L9) the problem?

**Comment by cawooda** [comment]
sure is @cawoodm 
fixed with the following: _hover: { bgColor: "yellow.400" },
